apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: k8s-speedtest-exporter
  annotations:
    github.com/project-slug: mattjmorrison-homelab/k8s-speedtest-exporter
spec:
  type: metrics-exporter
  owner: mattjmorrison-homelab
  system: monitoring
